---
# tasks file for satish.nginx
   - name: Install nginx
     apt: name=nginx  state=installed

   - name: Start nginx service
     service: name=nginx state=running

   - name: Create nginx default configuration
     template: src=default dest=/etc/nginx/sites-available/default
     notify: restart nginx
